name: Deply to server.
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: 192.168.1.6
        username: fwy13
        password: 130907
        port: 22
        script: whoami
