name: Deply to server.
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      run:  ssh -p 22 fwy13@192.168.1.6 echo fwy13 echo 130907
